"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var product_controller_1 = require("../controllers/product.controller");
var router = express.Router();
router.get("/all", product_controller_1.default.getProducts);
router.get("/get-by-id/:id", product_controller_1.default.getProductsById);
router.delete("/delete/:id", product_controller_1.default.removeProductById);
router.get("/search/:keyword", product_controller_1.default.getProductsByKeyword);
router.post("/create", product_controller_1.default.createProduct);
router.put("/update", product_controller_1.default.updateProduct);
router.post("/get-by-category", product_controller_1.default.getProductsByCategory);
exports.default = router;
